module.exports = {
  common: {
    errorToast: '.Toastify__toast--error',
    toastBody: '.Toastify__toast-body',
    closeToast: '.Toastify__close-button',
    spinner: '.spinner',
    noDataInfo: '.rt-noData',
    submitButton: 'button[type="submit"]',
  },
  navigation: {
    navigationTab: '.navigation__link',
  },
  pagination: {
    buttonPrevious: '.pagination-bottom .-previous button',
    buttonNext: '.pagination-bottom .-next button',
    pageSizeSelect: '.-pageSizeOptions select',
    jumpToPage: '.-pageJump input',
    totalPages: '.-totalPages',
  },
  modal: {
    title: '.builder-modal__title', 
  },
  authentication: {
    email: '#email',
    password: '#password',
    submitButton: 'button[type="submit"]',
    emailWarningMessage: 'p[class^=login-page__WarningMessage]',
    resetPasswordLink: 'a[class^="login-page__StyledLink"]',
    passwordResetButton: 'button[class^="common-builder-styles__Button"]',
    passwordResetMessage: '[class^="common-builder-styles__Info"]',
    passwordResetSuccessMessage: '[class^="common-builder-styles__SuccessMessage"]',
    logoutLink: 'header span[role="button"]',
    emailResetInput: '#email',
    userColumnName: '.rt-resizable-header-content',
    emailFilter: '.rt-tr .rt-th:nth-child(3) input',
    nameFilter: '.rt-tr .rt-th:nth-child(2) input',
    userDataInRow: '.rt-td > *',
    userDataMainRow: '.rt-tr-group',
    userPermissionsView: '.button-as-link.users-page__table-link',
    usernameInModal: 'h2.builder-modal__body',
    permissionsInModal: '.builder-modal__body--locale',
    closePermissionsModal: '.builder-modal__form button',
    deleteUserButton: '.users-page__list .button-label',
    editUserButton: '.users-page__list .rt-td .button--action',
    userEnabledClass: 'users-page__user-enabled',
    userDisabledClass: 'users-page__user-enabled--disabled',
    userDeleteModalTitle: '.builder-modal__title',
    userDeleteModalButton: '.builder-modal__form',
    userListColumn: '.rt-tr',
    userListEnabled: '.rt-td:nth-child(1) svg',
    userListNames: '.rt-td:nth-child(2)',
    userListEmails: '.rt-td:nth-child(3)',
    nameFieldCreate: 'input[name="name"]',
    emailFieldCreate: 'input[name="email"]',
    passwordFieldCreate: 'input[name="password"]',
    regionsLabelsCreate: 'div .users-page__territory',
    permissionsDropdownButtonCreate: index => `.users-page__create__form > div:nth-of-type(${index + 2}) .dropdownlist__button`,
    permissionsLevelOptionsCreate: index => `.users-page__create__form > div:nth-of-type(${index + 2}) .dropdownlist__items`,
    editUser : {
      enabled: '',
      name: '',
      password: ''
    }
  },
};
